### ISSUE TITLE
Gradients dithering?

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#16]
Right now, subtle gradients create some banding artifacts:
![2019-03-15-21:52:41](https://user-images.githubusercontent.com/23723605/54484445-623ed280-483d-11e9-816a-e70e0705698b.png)

Would it be out of scope for the project to apply some dither to the gradients, so that they would look smoother? Perhaps dithering could be enabled using a flag?

I think we would need to patch nanosvg to support dithering, among other things.

**Comment by poke1024** [comment]
We're talking about the `"texture"` mode, right? Then it's a problem with NanoSVG, indeed. I'm not sure how complex adding dithering there would be. It might be tricky because the error diffusion needs to be broken down several scanlines in the rasterizer.

Then again, it might be not that hard. What Mikko does is, probably for the sake of speed, is precompute a lookup table of 256 gradient colors, and then only use those. The relevant code is here:

https://github.com/memononen/nanosvg/blob/7cd94e31917e67ba5814fe6d4fcfd44b56a245d8/src/nanosvgrast.h#L1036

**Comment by poke1024** [comment]
I have a solution. Coming in the next few days.

**Comment by poke1024** [comment]
This is addressed now with 12133e82fa6c696f9346f60bfb468547ab11cb5d. It's also the default now, so it should work out of the box (performance is roughly the same as the old gradient drawing code from nanosvg, which surprised me a lot as the new code does a magnitude more memory writes). In extreme conditions, there still is banding, but in the context of what you can do without hdr it's pretty good.

**Comment by pdesaulniers** [comment]
Very nice! As you said, I do notice some banding in extreme cases, but it's definitely an improvement.

However, I'm not sure if the "best" gradient is handling alpha correctly. Here's a modified svg from the gradients demo:
[gradients.svg.zip](https://github.com/poke1024/tove2d/files/2999336/gradients.svg.zip)

It looks like this in the demo:
![2019-03-23-08:33:07](https://user-images.githubusercontent.com/23723605/54866107-7b1c1c00-4d46-11e9-91d8-79398a9c4ac4.png)

**Comment by pdesaulniers** [comment]
Maybe I'm pushing it a bit, since banding is pretty much indistinguishable in most cases, but: could there be an even higher quality mode, that handles extreme cases too? Perhaps using some sort of post-processing on the resulting gradient? 

Of course, that would be slow, but I suppose it could make sense for pre-rendered SVGs (i.e. flipbooks)

(I know that we should not expect TÖVE to produce print quality vector renderings, but still, I felt like asking :) )
