### ISSUE TITLE
'paint-order' attribute is ignored

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#25]
Modified blob demo SVGs: [gradient-circle.zip](https://github.com/poke1024/tove2d/files/3562816/gradient-circle.zip)

Expected result:

![2019-08-31-16:25:04](https://user-images.githubusercontent.com/23723605/64068846-0958d000-cc0c-11e9-8f0c-ef240eb3c3cd.jpg)

Current result:

![2019-08-31-16:26:47](https://user-images.githubusercontent.com/23723605/64068859-3a390500-cc0c-11e9-9bd4-ae558ba4aa33.jpg)

**Comment by poke1024** [comment]
Fixed with top of tree.

<img width="748" alt="paint-order" src="https://user-images.githubusercontent.com/11859538/64941275-743e1400-d866-11e9-82a8-2a465df19d66.png">

(the gpux mode needs vertex line mode, i.e. `table.insert(animations, tove.newAnimation(tween, "gpux", "vertex"))`, in the demo to look good).
