### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by flamendless** [poke1024/tove2d#3]
Is this module for löve or for godot? Im confused

**Comment by poke1024** [comment]
Yes, I know, it is confusing.

tove2d and this repo is intended for löve.

And yet, there's this `godot` folder in here. The `godot` folder ends up in this repository as a purely experimental part and it does not really belong here - I always wanted to make the Godot thing a different branch or a different repository, but didn't decide because it's so unfinished and I'm still undecided whether it has any value at all. Currently, it ends up being in here. I haven't worked on the Godot integration for quite some time and it's nothing but an experiment that has lots of open ends. Most users can just ignore that this repo contains this `godot` folder. I should really split this in different repos.

**Comment by flamendless** [comment]
okay, got it. thanks
